image: node:latest
# image: nikolaik/python-nodejs:latest

before_script:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install python3.8
  - cd ./reactapp    # enter the React app directory
  - rm -rf build     # remove the existing build
  - CI=true npm install     # install required packages

cache:
  paths:
    - node_modules/

stages:
  - test

test:
  stage: test
  script:
    - CI=true npm test
  only:
    # - TestPipeline
    - master
