image: node:latest

before_script:
  - cd ./reactapp    # enter the React app directory
  - rm -rf build     # remove the existing build
  - CI=true npm install     # install required packages

cache:
  paths:
    - node_modules/

stages:
  - test

test:
  stage: test
  script:
    - CI=true npm test
  only:
    - TestPipeline


# pages:
#   stage: deploy
#   cache:
#     paths:
#       - node_modules/
#   script:
#     - CI=false npm install
#     - npm run build
#     - rm -rf public
#     - cp build/index.html build/404.html
#     - mv build public
#   artifacts:
#     paths:
#       - public
#   only:
#     - TestPipeline